version: '3'

services:
  facade:
    build: ./facade-service
    ports:
      - "8000:8000"
    depends_on:
      - messages
      - logging

  logging:
    build: ./logging-service
    ports:
      - "8001:8000"

  messages:
    build: ./messages-service
    ports:
      - "8002:8000"